# Server
server.port=8080
  
  # DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_tracking
spring.datasource.username=postgres
spring.datasource.password=Aryan@364
spring.datasource.driver-class-name=org.postgresql.Driver
  
  # JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
  
  # App config
app.jwt.secret=7BsD1jmKQ8WQh7+rDalYavbmwjaLisrZAI6On0AvqHE=
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173

app.idle.radius-meters=100
app.idle.idle-threshold-minutes=60
app.idle.check-interval-ms=300000

app.threshold.daily-drive-minutes=480
  
  # Logging
logging.level.com.fleet.tracking=DEBUG

app.location-ping.retention-days=30
app.location-ping.cleanup-cron=0 30 1 * * *

app.alert.retention-days=90
app.alert.cleanup-cron=0 0 2 * * *